# Generated by Django 4.2.30 on 2026-07-08 23:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nomor_wa', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Format tidak valid. Nomor WA harus berupa angka 10-15 digit.', regex='^\\d{10,15}$')])),
                ('nama_lengkap', models.CharField(blank=True, max_length=150, null=True)),
                ('alamat_lengkap', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('status', models.CharField(choices=[('ANTRIAN', 'Dalam Antrian'), ('PERSIAPAN', 'Persiapan Pengiriman'), ('KIRIM', 'Sedang Dikirim'), ('SELESAI', 'Selesai'), ('BATAL', 'Dibatalkan')], db_index=True, default='ANTRIAN', max_length=20)),
                ('metode_pengiriman', models.CharField(choices=[('AMB', 'Ambil di Kandang'), ('ANT', 'Diantar ke Lokasi')], default='AMB', max_length=3)),
                ('metode_pembayaran', models.CharField(choices=[('CASH', 'Bayar di Tempat (Tunai)'), ('TRF', 'Transfer Bank')], default='CASH', max_length=4)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('jarak_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ongkir', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_harga', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bukti_pembayaran', models.ImageField(blank=True, null=True, upload_to='bukti_transfer/')),
                ('items_summary', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('kode_unik', models.CharField(max_length=50, unique=True)),
                ('kategori', models.CharField(max_length=100)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.PositiveIntegerField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='produk_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(default='Kelompok Tani Melati', max_length=100)),
                ('nomor_admin', models.CharField(default='08123456789', help_text='WA Notifikasi Fonnte', max_length=20)),
                ('alamat_toko', models.TextField(blank=True, default='Bukit Pinang, Samarinda')),
                ('hero_title', models.CharField(default='Inkubator DOC Berkualitas', max_length=255)),
                ('hero_description', models.TextField(default='Penyedia DOC dan Telur Tetas terbaik...')),
                ('rekening_bank', models.CharField(blank=True, max_length=100, null=True)),
                ('rekening_nama', models.CharField(blank=True, max_length=100, null=True)),
                ('biaya_per_km', models.IntegerField(default=5000)),
                ('latitude', models.CharField(blank=True, max_length=50, null=True)),
                ('longitude', models.CharField(blank=True, max_length=50, null=True)),
                ('jam_operasional', models.TextField(blank=True, default='Senin - Sabtu: 08.00 - 17.00 WITA')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='settings/')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuantitas', models.PositiveIntegerField()),
                ('harga_saat_beli', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='store.product')),
            ],
        ),
    ]
