# Generated by Django 4.2.30 on 2026-05-31 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='kategori',
            field=models.CharField(max_length=100),
        ),
    ]
