# Generated by Django 4.2.30 on 2026-05-31 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='produk_images/'),
        ),
    ]
