# Generated by Django 4.2.30 on 2026-07-10 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_ordercounter_alter_product_stok'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='alamat_lengkap',
        ),
        migrations.AddField(
            model_name='customuser',
            name='alamat',
            field=models.TextField(blank=True, help_text='Nama jalan, nomor rumah, RT/RW', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='kelurahan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
