# Generated by Django 4.2.30 on 2026-05-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
