# Generated by Django 4.2.30 on 2026-07-10 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_customuser_alamat_lengkap_customuser_alamat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='alamat',
            new_name='alamat_pengiriman',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='latitude',
            new_name='bank_pengirim',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='bukti_pembayaran',
            new_name='bukti_transfer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='jarak_km',
        ),
        migrations.RemoveField(
            model_name='order',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='order',
            name='ongkir',
        ),
        migrations.AddField(
            model_name='order',
            name='batas_waktu_dp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nama_rekening_pengirim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='nominal_dibayar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='tagihan_dp',
            field=models.IntegerField(default=0, help_text='Total DP yang harus dibayar'),
        ),
        migrations.AddField(
            model_name='order',
            name='waktu_bayar',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='metode_pembayaran',
            field=models.CharField(choices=[('CASH', 'Bayar di Tempat (Tunai)'), ('TRF', 'Transfer Bank')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='metode_pengiriman',
            field=models.CharField(choices=[('AMB', 'Ambil di Kandang'), ('ANT', 'Diantar ke Lokasi')], default='AMB', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('MENUNGGU_DP', 'Menunggu DP'), ('KONFIRMASI_DP', 'Menunggu Konfirmasi Pembayaran'), ('ANTRIAN', 'Masuk Daftar Antrean (PO)'), ('PERSIAPAN', 'Persiapan Pengiriman'), ('DIKIRIM', 'Sedang Dikirim'), ('SELESAI', 'Selesai'), ('BATAL', 'Dibatalkan')], db_index=True, default='MENUNGGU_DP', max_length=20),
        ),
    ]
