# Generated by Django 4.2.30 on 2026-05-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='alamat',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='nomor_hp',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='gambar',
            field=models.ImageField(blank=True, null=True, upload_to='produk_images/'),
        ),
    ]
