# Generated by Django 4.2.30 on 2026-07-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_order_metode_pembayaran_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='metode_pembayaran',
            field=models.CharField(choices=[('CASH', 'Bayar di Tempat (Tunai)'), ('TRF', 'Transfer Bank')], default='CASH', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='metode_pengiriman',
            field=models.CharField(choices=[('AMB', 'Ambil di Kandang'), ('ANT', 'Diantar ke Lokasi')], default='AMB', max_length=100),
        ),
    ]
