# Generated by Django 4.2.30 on 2026-06-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_alamat_order_nomor_hp_alter_product_gambar'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bukti_pembayaran',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_transfer/'),
        ),
        migrations.AddField(
            model_name='order',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='longitude',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='metode_pembayaran',
            field=models.CharField(choices=[('COD', 'Bayar di Tempat'), ('TF', 'Transfer')], default='COD', max_length=3),
        ),
        migrations.AddField(
            model_name='order',
            name='metode_pengiriman',
            field=models.CharField(choices=[('AMB', 'Ambil Sendiri'), ('ANT', 'Diantar ke Lokasi')], default='AMB', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='nomor_hp',
            field=models.CharField(max_length=20),
        ),
    ]
