# Generated by Django 4.2.30 on 2026-07-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_order_metode_pembayaran_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='dashboard_intro_text',
            field=models.TextField(default='Aplikasi web ini dibuat dengan sangat KILAT, demi memfasilitasi antusias rekan-rekan dalam melakukan pemesanan Telur ataupun DoC.\nHarap dimaklumkan dengan tampilan yang sangat sederhana, karena kami mengedepankan fungsionalitas.'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='dashboard_outro_text',
            field=models.TextField(default='Di kemudian hari, aplikasi ini akan dikembangkan untuk mendukung aktivitas kalian dalam beternak\ntentu pengembangan akan dilakukan secara bertahap.'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='dashboard_welcome_title',
            field=models.CharField(default='Selamat datang di Web Portal Kelompok Tani Melati.', max_length=255),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='syarat_doc',
            field=models.TextField(default='- Eceran minimal 10 ekor\n- Jenis Kelamin RANDOM.\n- yang dikirimkan anak ayam usia 3-7 hari, sudah di vaksin ND-IB.\n- sementara hanya dilayani untuk pulau jawa saja\n- ekspedisi KaLog Express atau Kantorpos layanan NextDay\n- tidak ada ready stock instant, semua dalam kondisi antrian'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='syarat_telur',
            field=models.TextField(default='- per 1kg kiriman, berisi 16 butir. boleh mix\n- pengiriman dari Banyuwangi, Jawa Timur\n- Garansi Pengiriman, simak Video berikut\n- Ekspedisi yang digaransi : Kantorpos atau Tiki\n- tidak ada ready stock instant, semua dalam kondisi antrian'),
        ),
    ]
