# Generated by Django 4.2.30 on 2026-06-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_bukti_pembayaran_order_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='jarak_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
