# Generated by Django 4.2.30 on 2026-06-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_order_jarak_km'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PRO', 'Proses'), ('SLS', 'Selesai'), ('BTL', 'Batal')], db_index=True, default='PRO', max_length=3),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', '-order_date'], name='store_order_status_c6db3b_idx'),
        ),
    ]
