# Generated by Django 4.2.30 on 2026-07-13 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_storesetting_dashboard_intro_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ekspedisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(help_text='Contoh: KaLog Express, Ambil Sendiri', max_length=100)),
                ('biaya', models.IntegerField(default=0, help_text='Isi 0 jika gratis (Ambil Sendiri)')),
                ('is_active', models.BooleanField(default=True, help_text='Centang untuk menampilkan di halaman pemesanan')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='biaya_ongkir',
            field=models.IntegerField(default=0),
        ),
    ]
