# Generated by Django 4.2.30 on 2026-06-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_order_order_date_alter_order_order_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(default='DOC Mart', max_length=100)),
                ('nomor_admin', models.CharField(default='0895704050703', help_text='Nomor WA untuk notifikasi pesanan (Fonnte)', max_length=20)),
                ('alamat_toko', models.TextField(blank=True, default='Jl. Peternakan No. 1, Desa Mulawarman')),
            ],
        ),
    ]
