# Generated by Django 4.2.30 on 2026-07-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_storesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='biaya_per_km',
            field=models.IntegerField(default=5000, help_text='Biaya pengiriman per kilometer (Rp)'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='hero_description',
            field=models.TextField(default='Langsung dari peternak lokal tersertifikasi. Kami memastikan genetik unggul, tingkat daya tetas tinggi, dan jaminan kesehatan ternak Anda.'),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='hero_title',
            field=models.CharField(default='Penyedia DOC & Telur Fertil Ayam KUB Unggulan', max_length=255),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='rekening_bank',
            field=models.CharField(default='BCA 1234 5678 90', max_length=100),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='rekening_nama',
            field=models.CharField(default='a.n. Kelompok Tani Melati Official', max_length=100),
        ),
        migrations.AlterField(
            model_name='storesetting',
            name='alamat_toko',
            field=models.TextField(blank=True, default='H32W+FCW Bukit Pinang, Kota Samarinda, Kalimantan Timur'),
        ),
    ]
