# Generated by Django 4.2.30 on 2026-07-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_storesetting_biaya_per_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='latitude',
            field=models.CharField(default='-0.5020', help_text='Latitude lokasi toko', max_length=50),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='longitude',
            field=models.CharField(default='117.1530', help_text='Longitude lokasi toko', max_length=50),
        ),
    ]
