# Generated by Django 4.2.30 on 2026-07-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_storesetting_latitude_storesetting_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Gambar latar belakang halaman utama', null=True, upload_to='settings/'),
        ),
    ]
