# Generated by Django 4.2.30 on 2026-07-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_storesetting_hero_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesetting',
            name='alamat_toko',
            field=models.TextField(blank=True, default='Bukit Pinang, Kota Samarinda, Kalimantan Timur'),
        ),
    ]
