# Generated by Django 4.2.30 on 2026-07-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_storesetting_alamat_toko'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='jam_operasional',
            field=models.TextField(blank=True, default='Senin - Sabtu: 08.00 - 17.00 WITA\nMinggu: Tutup (Kecuali Janji Temu)'),
        ),
    ]
