services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./custom-mysql.cnf:/etc/mysql/conf.d/custom-mysql.cnf:ro
    # BLOK HEALTHCHECK
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          memory: 400M

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    # Ganti runserver dengan Gunicorn & jalankan collectstatic otomatis
    command: sh -c "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000" # Tutup port publik, biarkan hanya Nginx yang bisa mengakses
    env_file:
      - .env
    restart: always
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # TAMBAHKAN KONTAINER NGINX INI
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "8810:80" # VPS Port 8810 diarahkan ke Nginx Port 80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
    depends_on:
      - web